name: build-test-deploy

on: push
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: actions/checkout@v5

      - name: install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - run: npm install
      - run: npm run build
      
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: actions/checkout@v5

      - name: install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - run: npm install
      - run: npm test


  deploy:
    needs: test

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - name: checkout repo code
        uses: actions/checkout@v5

      - name: install nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: install dependencies
        run: npm install

      - name: build application
        run: npm run build

      - name: configure github pages
        uses: actions/configure-pages@v5

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './out'

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v5

