name: hello-world-cicd
on: push

jobs:
  hello-world-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo code
        uses: action/checkout@v4
      
      - run: echo "$(cat hello_world.txt)"
         

